### ISSUE TITLE
[São Paulo] Full Stack Developer na CâmbioStore

### ISSUE THREAD

**Issue by perylemke** [RubyFloripa/jobs#1]
## Descrição da vaga

Full Stack Developer

## Local

Remoto ou Escritório, São Paulo - Vila Olímpia

## Requisitos

**Obrigatórios:**
- Sólida experiência em Ruby on Rails
- Amplo conhecimento em HTML, CSS, JavaScript e React/AngularJS
- Experiência com Desenvolvimento Ágil de Software (Scrum, Kanban, XP, Lean)
- Experiência com TDD (Test Driven Development)

## Contratação

PJ - R$ 5.000 ~ R$ 9.000

## Empresa

Somos uma empresa de câmbio online, chamada Câmbio Store. Nascemos em 2015 com um objetivo muito simples, trazer a melhor cotação de dólar para os nossos usuários. Somos uma empresa convencional, faturamos e queremos ser rentáveis, sempre.

Desenvolvemos o nosso MVP, nosso produto conseguiu uma boa tração, e agora procuramos afinar os nossos processos através de tecnologia.

Procuramos pessoas pragmáticas, reconhecemos a importância de iterações rápidas e “failing fast”. Seguimos os princípios do manifesto “agile”, na medida que isto torne o nosso time realmente ágil.

Além do nossa plataforma de câmbio, estamos desenvolvendo alguns outros produtos, eis a necessidade da expansão.

## Como se candidatar

Para se candidatar a vaga favor utilizar o seguinte formulário: https://cambiostore.typeform.com/to/nrw38f

**Comment by wevtimoteo** [comment]
Como a vaga não foi atualizada com o status da contratação, estou fechando a mesma :+1:
