### ISSUE TITLE
[Remote] Backend Developer at TechLatam

### ISSUE THREAD

**Issue by mejiaro** [RubyFloripa/jobs#11]
## Job description

We're looking for intermediate-level developers for full-time remote positions. Our projects involve small Latin American startups and a few big international companies. Decisions about the best way to solve a requirement will be up to you and your teammates.

## Local

Remote.

## Benefits

- Participation in technology conferences, workshops, and meetups.
- 21 days of vacation
- Access to online courses like RubyTapas and Udemy.

## Requirements

**Mandatory:**
- At least 1 year of experience working with Ruby and Rails.
- Fluent in English or Spanish.
- Follow clean coding practices using Rubocop or similar conventions.
- Experience with data storage solutions.

**Good to have:**
- You've built an API for mobile and web clients.
- Experience in HTML and Javascript.
- The first line you write when starting a feature is a test.
- Knowledge in building scalable systems.

## Contract

Agreed between the parties

## Our company

We operate from El Salvador focusing in Latin America. We specialize in helping entrepreneurs with original ideas for startups and seek to innovate, connect and boost businesses. Find out more on our website [techlatam.la](techlatam.la)

## How to apply 

Send an email with the subject "Backend Developer - TL" to  jobs@techlatam.la. Please attach your CV and Github profile link.

**Comment by nelsonmfinda** [comment]
@wevtimoteo Hi, TechLatam are now hiring?

**Comment by wevtimoteo** [comment]
@nelsonmfinda you can ask @mejiaro (the issue's author) directly :dancer: 

Is it still hiring @mejiaro?

**Comment by mejiaro** [comment]
Hey guys, sorry, not anymore. I quit the company last year and it was closed in December due to legal problems.
