### ISSUE TITLE
[Florianópolis] Fullstack Developer at KM Online

### ISSUE THREAD

**Issue by wevtimoteo** [RubyFloripa/jobs#12]
![KM Online](https://user-images.githubusercontent.com/645452/45556100-d78b0580-b810-11e8-8314-754505544a8c.png)

## Description

We're building a fullstack development team, searching for autonomous & responsible developers, always hungry for new technologies and great problem-solver.

KM Online is a fast-growing startup that is being accelerated by [Darwin Startups](https://darwinstartups.com/), we seek to build a team with strong and engaged culture.

### Location

Florianópolis - Saco Grande ([ACATE](https://www.acate.com.br/))

## Responsibilities

* Develop and maintain applications
* Writing and reviewing applications code
* Monitor and manage servers infrastructure

### Qualifications

* 1+ year experience working on development of a web application
* NoSQL and general database knowledge (we use MongoDB)
* Solid knowledge of testing principles
* Interest or abilities in functional programming
* Strong verbal and written communication skills
* Ability to work in GNU/Unix environment
* Experience in Version Control Systems is a must (`git` specifically)

### Bonus

* Mobile development (Android or iOS)
* Experience writing and using REST APIs
* Geolocation (GIS)
* AWS
* Elixir
* Message Broker concepts
* Experience with Angular, React or Vue
* Heroku
* Docker
* Big Data
* Experience with scalability problems

## Our stack

* Ruby
* Rails
* Elixir
* MongoDB
* AWS SNS
* AWS SQS
* Redis
* Javascript
* Google Maps API
* Google Roads API
* Sass
* Git
* Linux
* RSpec
* ExUnit
* Docker
* Java (Android)
* Objective-c (iOS)

## Hiring

CLT - Salary according to experience

### Benefits

* Small Team
* Flat Hierarchy
* Conferences
* Health Care
* Salary according with experience (CLT)
* Flexibility to work remotely
* Proper timing to collaborate in building company's culture
* Opportunity to build product backlog with us

## Our company

Founded at 2017, at Florianópolis, KM Online has an objective to simplify expense reporting and displacement reimbursement, using our Cloud platform, composed by mobile apps and web access. See more at [kmonline.com.br](https://kmonline.com.br)

## How to apply

Mail us with your [LinkedIn](https://linkedin.com) and [Github](https://github.com) profile: [jobs@kmonline.com.br](mailto:jobs@kmonline.com.br)

**Comment by GusGA** [comment]
Still hiring?

**Comment by GusGA** [comment]
Still hiring @wevtimoteo ?

**Comment by wevtimoteo** [comment]
@GusGA I'm not working at [kmonline](https://kmonline.com.br) anymore, currently, I'm involved with [EbertApp.io](https://ebertapp.io) product.

If you're still interested in KM Online, @leandroh and @avelino can answer your question :)

**Comment by GusGA** [comment]
Ok, Thanks @wevtimoteo 

Sorry for the inconvenience.
