### ISSUE TITLE
[Curitiba] Desenvolvedor Ruby on Rails na Trackmob

### ISSUE THREAD

**Issue by MicaelaMateos03** [RubyFloripa/jobs#18]
[CURITIBA] Desenvolvedor Ruby on Rails na Trackmob

## Descrição da vaga

Quer usar seu conhecimento para transformar o mundo em um lugar melhor?

Somos uma startup que desenvolve tecnologia para que ONGs do mundo todo consigam mais doações e possam impactar ainda mais com seus projetos sociais que transformam vidas. Hoje já conquistamos quase meio milhão de doadores para elas e esse número só tende a crescer.

Aqui na Trackmob, você irá trabalhar em um ambiente positivo e com uma equipe incrível que busca conhecimento todo santo dia e com espaço para crescimento profissional e global. Nós acreditamos na tecnologia como uma grande aliada para aumentar a cultura da doação no Brasil e no mundo.

Estamos buscando um Engenheiro de Software talentoso que domine lógica de programação e Ruby on Rails para abraçar também essa causa. Nós da Trackmob queremos que você faça fazer parte disso. Vem ser Trackmober!

## Local

Remoto ou Escritório, Curitiba - Centro Cívico

## Benefícios

- Trabalhar em uma startup que ajuda a transformar a vida de milhões de pessoas e muda o mundo! ♥
- Time incrível, dinâmico, colaborativo e super receptivo! #vemsertrackmober
- Temos uma estrutura de trabalho horizontal, diferente da hierarquia tradicional;
- Prezamos pelo seu desenvolvimento profissional, desta forma você terá constantemente feedbacks e direcionamentos com a liderança para a sua evolução!
- Office em uma região de fácil acesso

## Requisitos

- Experiência avançada com programação em Ruby on Rails, preferencialmente pelo menos 4 anos de experiência prévia.Conhecimento avançado com AWS.
- Ter experiência com metodologias ágeis (XP, SCRUM, Kanban).
- Conhecimento sólido em programação orientada à objetos.
- Conhecimento básico em front-end (JavaScript, HTML5, and CSS3).
- Conhecimento e experiência avançada com desenvolvimento de APIs REST.
- Experiência avançada com algum framework de testes (preferencialmente RSpec).
- Conhecimento e experiência avançada com PostgreSQL e Redis.
- Experiência com sidekiq.
- Inglês (leitura/escuta).

## Contratação

PJ a combinar

## Como se candidatar

Se inscreva aqui --------> https://goo.gl/c8czEv

![AF_Vaga_Desenvolvedor (1)](https://user-images.githubusercontent.com/35700931/55009338-23d5b000-4fc1-11e9-9483-f6a56a410f7b.png)

**Comment by wevtimoteo** [comment]
@MicaelaMateos03 não se esqueçam de incluir a Trackmob no catálogo de empresas do repositório GuruBR: https://github.com/guru-br/catalogo_empresas#paran%C3%A1-pr
