### ISSUE TITLE
[Florianópolis] Fullstack Developer at SumOne

### ISSUE THREAD

**Issue by jplethier** [RubyFloripa/jobs#4]
## Descrição da vaga

Estamos em busca de mais um SumOner para o nosso time!

Ser um SumOner é fazer parte de uma empresa que quer revolucionar o varejo físico através de soluções que conectem marcas e clientes, baseadas em relações ganha-ganha. É trabalhar em um ambiente jovem, descontraído e repleto de desafios. É ser freak por resultados, porém sem nunca esquecer de cultivar as relações humanas, a parceria e os momentos felizes. É querer crescer junto e construir com a gente o nosso sonho.

Então, se você gosta de grandes desafios, quer fazer a diferença e trabalhar com pessoas extraordinárias; a SumOne é o seu lugar!

Como Software Engineer você fará parte da nosso time de Produto e será responsável por construir soluções que irão revolucionar o varejo físico. Estamos em busca de um profissional apaixonado por desenvolvimento de software e que tenha grandes aspirações em se tornar cada vez melhor no que faz, e melhor que isso, que não apenas queira, mas que esteja disposto a se manter em constante estado de aprendizado e adaptação.

## Local

Presencial, Florianópolis - Itacorubi

## Benefícios

- Salário fixo compatível com mercado;
- Vale refeição/alimentação;
- Vale transporte integral;
- Autonomia e flexibilidade;
- Ambiente de trabalho descontraído e divertido;
- No dress code;

## Requisitos

**Obrigatórios:**
- Experiência em desenvolvimento de softwares;
- Domínio da linguagem Ruby e do framework Ruby on Rails;
- Conhecimentos em temas de ciências da computação como arquitetura de sistemas, estrutura de dados, redes, algoritmos;
- Mindset ágil e XP;
- Visão holística do processo de desenvolvimento de software.

**Desejáveis:**
- Formação na área;
- Conhecimento de operação e volume de dados;
- Postgres e NoSQL;
- Javascript e JQuery;
- Conhecimentos em Python e PyQt

**Diferenciais:**
- projetos opensource

## Contratação

CLT

## Nossa empresa

Aqui na SumOne somos uma empresa em busca de revolucionar o varejo oferecendo uma plataforma de marketing e relacionamento digital para o mundo físico.

## Como se candidatar

Através do link https://sumone.workable.com/jobs/555730

**Comment by pedRo-shd** [comment]
Me candidatei a vaga, enviei o projeto solicitado, mas me retornaram dizendo que agora a vaga está em stand-by,nesse caso acho justo retirar o anúncio desta vaga,
