### ISSUE TITLE
[Florianópolis] Fullstack Developer na Go Good

### ISSUE THREAD

**Issue by MartinaCarvalho** [RubyFloripa/jobs#5]
## Descrição da vaga

O time da Go Good está crescendo \o/

Procuramos um profissional para a área de desenvolvimento com interesse em resolver problemas complexos e que também seja capaz de atuar em todas as etapas do desenvolvimento web!

A pessoa contratada terá a responsabilidade de analisar e desenvolver funcionalidades na plataforma e o desafio de participar das principais decisões de produto e tecnologia.

Já temos uma plataforma completa de gamificação para mudança de hábitos e neste momento estamos aprimorando a experiência dos usuários.

Utilizamos Ruby on Rails para o backend, AngularJS para o frontend web, e React-Native para o frontend mobile.

## Local

Florianópolis - LinkLab da Acate no Primavera Garden

## Requisitos

**Obrigatórios:**

- Para essa oportunidade, buscamos talentos com experiência em desenvolvimento web (Front e Back-End) e conhecimento de: *Ruby on Rails; *CSS; *Javascript.

**Desejáveis:**
-

**Diferenciais:**
- equipe enxuta, mas fora da curva;
- processo de aceleração;
- participação nas decisões de produto e tecnologia.

## Contratação

CLT

## Nossa empresa

Somos uma startup em forte processo de aceleração. Oferecemos aos nossos clientes uma plataforma de bem-estar orientada a dados e gamificação, que incentiva os funcionários a criar e manter hábitos saudáveis, melhorando seu estilo de vida de modo personalizado e reduzindo os custos com saúde.
Atualmente estamos participando do programa de inovação aberta no Link Lab da Acate / Florianópolis.

Nossos desafios são criar experiências que engagem o usuário e utilizar dados complexos de saúde e bem estar para oferecer resultados em mudança de hábitos para os usuários e em diminuição do custo de saúde para as empreas.

## Como se candidatar

Por favor envie um email para vempra@gogood.social com seu Github, currículo ou LinkedIn - enviar no assunto: Fullstack Developer

**Comment by wevtimoteo** [comment]
@jrgvf I don't know why Github delivered this notification for you

**Comment by jrgvf** [comment]
Ok. No problem.

Good night.
Em qui, 1 de mar de 2018 às 22:52, Weverton do Couto Timoteo <
notifications@github.com> escreveu:
